Added GetSampledValue examples for SdsClientLibraries and SdsRestApi
gtripsas-osi/OSI-Samples pull request #1
Opened 2019-06-05 18:25 UTC by gtripsas-osi

2019-06-05 21:44 UTC, kanepenley commented on ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/Program.cs
> +                    allEvents[i] = UpdateWave(allEvents[i], multiplier: 5);
I wonder if it's confusing that this function is called UpdateWave when we're replacing. I'm probably overthinking it.

2019-06-05 21:49 UTC, gtripsas-osi commented on ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/Program.cs
> +                    allEvents[i] = UpdateWave(allEvents[i], multiplier: 5);
I could see how it could be argued as confusing. But for our purposes the solution would be to have a structurally identical method by another name. We could rename the existing method to something more generic. I just wanted to limit changing other people's code.

2019-06-05 21:50 UTC, kanepenley commented on ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/Program.cs
> +                    allEvents[i] = UpdateWave(allEvents[i], multiplier: 5);
I think we can roll with it as is. Just wanted to see what you thought.

2019-06-05 21:55 UTC, kanepenley commented on ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/Program.cs
> +                // Step 15
we need to straight up remove this rather than comment it out.

2019-06-05 22:09 UTC, kanepenley commented on ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/Program.cs
> +                // Step 15
we should remove it from the REST client too. that functionality is going away.

2019-06-05 22:25 UTC, gtripsas-osi commented on ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/Program.cs
> +                // Step 15
Alright, I'll remove them. The type id and value stuff yeah?

2019-06-05 22:31 UTC, gtripsas-osi commented on ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/Program.cs
> +                // Step 15
Am I to just flat out remove the entire Step 14 that revolves around Updating Stream Type based on SdsStreamView?

2019-06-07 22:06 UTC, kanepenley requested changes

2019-06-07 22:06 UTC, kanepenley commented on ocs_samples/basic_samples/SDS/DotNet/SdsClientLibraries/SdsClientLibraries/Program.cs
> +                // Step 15
Just the calls that try to filter Types.

2019-06-07 22:06 UTC, kanepenley commented on ocs_samples/basic_samples/SDS/Java/sdsjava/src/main/java/com/github/osisoft/sdsjava/WaveData.java
> +        //double radians = (((double) milliSec % intervalInMilliSec) / intervalInMilliSec) * 2 * Math.PI;
can we get rid of commented stuff?

2019-06-11 17:49 UTC, closed without merging